backend:
  name: github
  repo: nolabelventures/nolabelventures.github.io # Path to your GitHub repository
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://us-central1-nolabelventures.cloudfunctions.net
  auth_endpoint: /oauth/auth

media_folder: "assets/uploads"

collections:
  - name: home
    label: Home Page
    files:
      - name: intro
        label: Intro Section
        identifier_field: content
        file: _data/intro.yml
        editor:
          preview: false
        fields:
          - label: Content
            name: content
            widget: markdown

      - name: founder
        label: Founder Section
        identifier_field: content
        file: _data/about.yml
        editor:
          preview: false
        fields:
          - label: Content
            name: content
            widget: markdown

      - name: faqs
        label: FAQs
        extension: yml
        file: _data/faqs.yml
        editor:
          preview: false
        fields:
          - label: FAQ
            name: faq
            widget: list
            identifier_field: question
            fields:
              - {
                  label: "Question",
                  name: "question",
                  widget: "text",
                }
              - {
                  label: "Answer",
                  name: "answer",
                  widget: "text",
                }

      - name: "portfolio_items"
        label: "Portfolio Items"
        label_singular: "Portfolio Item"
        create: true
        file: "_data/portfolio.yml"
        widget: "list"
        editor:
          preview: false
        fields:
          - label: portfolio
            name: portfolio
            identifier_field: title
            widget: list
            fields:
              - {
                  label: "Title",
                  name: "title",
                  widget: "text",
                }
              - { label: "URL", name: "url", widget: "text", required: false }
              - {
                  label: "Description",
                  name: "description",
                  widget: "text",
                }

  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: title
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          choose_url: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Related Articles"
        name: "related"
        widget: "list"
        max: 3
        label_singular: "Article"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "content", widget: "text" }
          - {
              label: "Image",
              name: "thumbnail",
              widget: "image",
              choose_url: false,
              allow_multiple: false,
            }
          - {
              label: "Related Article Link",
              name: "link",
              widget: "relation",
              collection: "blog",
              search_fields: ["title"],
              display_fields: ["title"],
              value_field: "{{slug}}",
              multpile: true,
            }

  - name: other
    label: Other Pages
    files:
      - label: "Privacy Policy"
        name: "privacy_policy"
        file: "privacy-policy.md"
        fields:
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "default",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
